### ISSUE TITLE
"it's" should be "its"

### ISSUE THREAD

**Issue by yttrian** [woltapp/arrow-detekt-rules#29]
https://github.com/woltapp/arrow-detekt-rules/blob/208e7cc698a95215ce73e26176a5b69e5fa59bfe/src/main/kotlin/com/wolt/arrow/detekt/rules/NoEffectScopeBindableValueAsStatement.kt#L31

"it's" is a contraction of "it is" or "it has", while "its" is the possessive form of "it"

Sorry to be pedantic, it just sort of a bugged me, but seemed too small for a full PR.

**Comment by diastremskii** [comment]
Damn, sorry for leaving it open for a while. Thanks for opening the issue! Fixed in release 0.4.0
