### ISSUE TITLE
Property 'ArrowRuleSet' is misspelled or does not exist.

### ISSUE THREAD

**Issue by ffcactus** [woltapp/arrow-detekt-rules#36]
When I followed the readme to try to enable this plugin, I got this error:

> Property 'ArrowRuleSet' is misspelled or does not exist.

The following content is added to my detekt configuration file (detekt-config-overrides.yml):

```
ArrowRuleSet:
     NoEffectScopeBindableValueAsStatement:
           active: true
```

ArrowRuleSet a top most option (without any space ahead). The configuration file is used like this:
>     detekt {
>         toolVersion = detektVersion
>         autoCorrect = true
>         buildUponDefaultConfig = true
>         config.from("$rootDir/gradle/detekt-config-overrides.yml")
>     }

**Comment by diastremskii** [comment]
Hey @ffcactus! I tried to reproduce it with the same config [here](https://github.com/diastremskii/arrow-detekt-rules-issue-36) and it didn't reproduce :(
Was the plugin added as `detektPlugins("com.wolt.arrow.detekt:rules:*VERSION*")`?
Feel free to adjust the said repo if something is missing to reproduce the issue

**Comment by diastremskii** [comment]
Closing for now, feel free to reopen/update the repo with example

**Comment by pseiferth** [comment]
Not sure if anybody looks at this ancient issue, but I am running into the same problem.

```> Task :app:detektMain FAILED
Property 'ArrowRuleSet' is misspelled or does not exist. This error may also indicate a detekt plugin is necessary to handle the 'ArrowRuleSet' key.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:detektMain'.
> Run failed with 1 invalid config property.
        - Property 'ArrowRuleSet' is misspelled or does not exist. This error may also indicate a detekt plugin is necessary to handle the 'ArrowRuleSet' key.
```

However, my setup is completely different. I am using detekt 2.0.0-alpha.1 version and use it via a gradle conventions plugin (see code below). My current guess is, that arrow-detekt-rules does not support the latest detekt versions. 

```
import dev.detekt.gradle.extensions.DetektExtension
import org.gradle.api.Plugin
import org.gradle.api.Project
import org.gradle.kotlin.dsl.dependencies
import org.gradle.kotlin.dsl.getByType

class MyPlugin : Plugin<Project> {
    override fun apply(target: Project) = with(target) {
        pluginManager.apply("dev.detekt")
        dependencies {
            "detektPlugins"("dev.detekt:detekt-rules-ktlint-wrapper:2.0.0-alpha.1")
            "detektPlugins"("com.wolt.arrow.detekt:rules:0.5.0")
        }

        val ext = extensions.getByType<DetektExtension>().apply { 
            config.setFrom("${project.rootDir}/detekt.yml")
            buildUponDefaultConfig.set(true)
        }
    }
}
```
